AspnetBBS/Controllers/NoteController.cs
using System.Linq;
using AspnetBBS.DataContext;
using AspnetBBS.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AspnetBBS.Controllers
{
    public class NoteController : Controller
    {
        /// <summary>
        /// Note list
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            if(HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                //No login
                return RedirectToAction("Login", "Account");
            }           
            //instead of var list = new List<Note>();
            using (var db = new AppDbContext())
            {
                // 1) get all data in note table
                var list = db.Notes.ToList();
                list.Reverse();
                return View(list);


                // 2) get all notes joining with other table (not working)
                //var list = db.Notes.Join(db.Users,
                //    n => n.UserNo,
                //    u => u.UserNo,
                //    (n, u) => new { n.NoteNo, n.NoteTitle, n.NoteContents, n.UserNo, u.UserName });
                //return View(list);


            }           
        }
        /// <summary>
        /// Note details
        /// </summary>
        /// <param name="noteNo"></param>
        /// <returns></returns>
        public IActionResult Detail(int noteNo)
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                //No login
                return RedirectToAction("Login", "Account");
            }
            using (var db = new AppDbContext())
            {
                var note = db.Notes.FirstOrDefault(n => n.NoteNo.Equals(noteNo));
                return View(note);
            }
        }
        /// <summary>
        /// Return add page
        /// </summary>
        /// <returns>Add page</returns>
        public IActionResult Add()
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                // without login
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        /// <summary>
        /// Add note to DB
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Add(Note model)
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                // without login
                return RedirectToAction("Login", "Account");
            }
            //null의 가능성 때문에 에러: 명시적 변환이 있을 수 있다고 하면서 에러
            //위에 null 검사했는데 또?? 나중에 identity를 통해 중복된 코드 고칠 예정
            //model.UserNo = HttpContext.Session.GetInt32("USER_LOGIN_KEY");
            model.UserNo = int.Parse(HttpContext.Session.GetInt32("USER_LOGIN_KEY").ToString());
            if (ModelState.IsValid)
            {
                using (var db = new AppDbContext())
                {
                    db.Notes.Add(model);
                    // instead of db.SaveChanges(); 
                    if (db.SaveChanges() > 0)
                    {
                        return Redirect("Index");
                    }                          
                }
                ModelState.AddModelError(string.Empty, "Sorry, we cannot save the note");
            }
            return View(model);
        }
        /// <summary>
        /// Edit
        [HttpGet]
        public IActionResult Edit(int noteNo)
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                //No login
                return RedirectToAction("Login", "Account");
            }
            using(var db = new AppDbContext())
            {
                var note = db.Notes.FirstOrDefault(n => n.NoteNo.Equals(noteNo));
                return View(note);
            }          
        }

        /// <summary>
        /// Edit 코드 추가 2019 01 25
        /// </summary>
        /// <param name="noteNo"></param>
        /// <param name="note"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Edit(int noteNo, Note note)
        {
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                //No login
                return RedirectToAction("Login", "Account");
            }
            note.UserNo = int.Parse(HttpContext.Session.GetInt32("USER_LOGIN_KEY").ToString());
            if (ModelState.IsValid)
            {
                var db = new AppDbContext();
                db.Notes.Update(note);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }
        /// <summary>
        /// Delete
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Delete(int noteNo)
        {
            //컨펌 메시지에서 확인을 누르면 이 메소드가 트리거 됨
            //파라미터로 글 번호와 컨펌 메시지의 결과가 들어와야함
            if (HttpContext.Session.GetInt32("USER_LOGIN_KEY") == null)
            {
                //No login
                return RedirectToAction("Login", "Account");
            }

            using (var db = new AppDbContext())
            {
                var note = db.Notes.FirstOrDefault(n => n.NoteNo.Equals(noteNo));
                db.Notes.Remove(note);

                if (db.SaveChanges() > 0)
                {
                    return Redirect("Index");
                }
                ModelState.AddModelError(string.Empty, "Sorry, we cannot delete the note");
            }
            return View();
        }
    }
}

AspnetBBS/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspnetBBS</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/trumbowyg/dist/ui/trumbowyg.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AspnetBBS</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Note" asp-action="Index">Note</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.Session.GetInt32("USER_LOGIN_KEY") == null)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
    </div>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/trumbowyg/dist/trumbowyg.min.js"></script>
        <script src="~/lib/trumbowyg/dist/plugins/upload/trumbowyg.upload.js"></script>
        @*<script src="~/lib/trumbowyg/dist/langs/ko.min.js"></script> 에디터 한글안내 hover *@
        @* site.js 가서 localization language 관련 jason 형식으로 옵션값 지정*@
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/delete.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/delete.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>